export const dummyUnits = [
  {
    name: "Introduction to Mathematics",
    code: "MATH101",
    description:
      "Basic principles of mathematics, including algebra and geometry.",
    students: [],
    lecturer: "Dr. Alice Johnson",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "1",
  },
  {
    name: "Introduction to Physics",
    code: "PHYS101",
    description: "Fundamentals of physics, covering motion, energy, and waves.",
    students: [],
    lecturer: "Dr. Bob Smith",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "2",
  },
  {
    name: "Introduction to Chemistry",
    code: "CHEM101",
    description:
      "Basic concepts in chemistry, including atoms, molecules, and reactions.",
    students: [],
    lecturer: "Dr. Carol White",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "3",
  },
  {
    name: "Introduction to Biology",
    code: "BIO101",
    description:
      "Principles of biology, including cell structure, genetics, and evolution.",
    students: [],
    lecturer: "Dr. David Brown",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "4",
  },
  {
    name: "Introduction to Computer Science",
    code: "CS101",
    description:
      "Foundations of computer science, including programming and algorithms.",
    students: [],
    lecturer: "Dr. Emma Green",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "5",
  },
  {
    name: "Introduction to Economics",
    code: "ECON101",
    description:
      "Basic economic principles, including supply and demand, and market structures.",
    students: [],
    lecturer: "Dr. Frank Harris",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "6",
  },
  {
    name: "Introduction to History",
    code: "HIST101",
    description: "Overview of major historical events and civilizations.",
    students: [],
    lecturer: "Dr. Grace Lewis",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "7",
  },
  {
    name: "Introduction to Literature",
    code: "LIT101",
    description:
      "Study of classic and modern literature, including analysis and interpretation.",
    students: [],
    lecturer: "Dr. Henry Clark",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "8",
  },
  {
    name: "Introduction to Philosophy",
    code: "PHIL101",
    description:
      "Introduction to philosophical thinking, including ethics and logic.",
    students: [],
    lecturer: "Dr. Ivy Martinez",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "9",
  },
  {
    name: "Introduction to Psychology",
    code: "PSY101",
    description:
      "Basic principles of psychology, including cognition, behavior, and emotion.",
    students: [],
    lecturer: "Dr. Jack Walker",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "10",
  },
];

export type IDummyUnit = (typeof dummyUnits)[0];

export const dummyLecturers = [
  {
    name: "Dr. Alice Johnson",
    email: "alice.johnson@example.com",
    phone: "123-456-7890",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "1",
  },
  {
    name: "Dr. Bob Smith",
    email: "bob.smith@example.com",
    phone: "234-567-8901",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "2",
  },
  {
    name: "Dr. Carol White",
    email: "carol.white@example.com",
    phone: "345-678-9012",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "3",
  },
  {
    name: "Dr. David Brown",
    email: "david.brown@example.com",
    phone: "456-789-0123",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "4",
  },
  {
    name: "Dr. Emma Green",
    email: "emma.green@example.com",
    phone: "567-890-1234",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "5",
  },
  {
    name: "Dr. Frank Harris",
    email: "frank.harris@example.com",
    phone: "678-901-2345",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "6",
  },
  {
    name: "Dr. Grace Lewis",
    email: "grace.lewis@example.com",
    phone: "789-012-3456",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "7",
  },
  {
    name: "Dr. Henry Clark",
    email: "henry.clark@example.com",
    phone: "890-123-4567",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "8",
  },
  {
    name: "Dr. Ivy Martinez",
    email: "ivy.martinez@example.com",
    phone: "901-234-5678",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "9",
  },
  {
    name: "Dr. Jack Walker",
    email: "jack.walker@example.com",
    phone: "012-345-6789",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "10",
  },
];

export type IDummyLecturer = (typeof dummyLecturers)[0];

export const dummyStudents = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "111-222-3333",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "1",
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "222-333-4444",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "2",
  },
  {
    name: "Michael Brown",
    email: "michael.brown@example.com",
    phone: "333-444-5555",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "3",
  },
  {
    name: "Emily Davis",
    email: "emily.davis@example.com",
    phone: "444-555-6666",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "4",
  },
  {
    name: "Christopher Wilson",
    email: "christopher.wilson@example.com",
    phone: "555-666-7777",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "5",
  },
  {
    name: "Amanda Johnson",
    email: "amanda.johnson@example.com",
    phone: "666-777-8888",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "6",
  },
  {
    name: "Joshua Lee",
    email: "joshua.lee@example.com",
    phone: "777-888-9999",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "7",
  },
  {
    name: "Sarah Martinez",
    email: "sarah.martinez@example.com",
    phone: "888-999-0000",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "8",
  },
  {
    name: "Daniel Garcia",
    email: "daniel.garcia@example.com",
    phone: "999-000-1111",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "9",
  },
  {
    name: "Jessica Rodriguez",
    email: "jessica.rodriguez@example.com",
    phone: "000-111-2222",
    units: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "10",
  },
];

export type IDummyStudent = (typeof dummyStudents)[0];
export const dummyClasses = [
  {
    name: "Mathematics 101",
    code: "MATH101C",
    description: "Introductory mathematics class.",
    lecturer: "Dr. Alice Johnson",
    students: [],
    unit: "Introduction to Mathematics",
    startTime: new Date("2024-09-01T08:00:00"),
    endTime: new Date("2024-12-15T10:00:00"),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "1",
  },
  {
    name: "Physics 101",
    code: "PHYS101C",
    description: "Fundamentals of physics.",
    lecturer: "Dr. Bob Smith",
    students: [],
    unit: "Introduction to Physics",
    startTime: new Date("2024-09-01T10:00:00"),
    endTime: new Date("2024-12-15T12:00:00"),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "2",
  },
  {
    name: "Chemistry 101",
    code: "CHEM101C",
    description: "Basic chemistry concepts.",
    lecturer: "Dr. Carol White",
    students: [],
    unit: "Introduction to Chemistry",
    startTime: new Date("2024-09-01T12:00:00"),
    endTime: new Date("2024-12-15T14:00:00"),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "3",
  },
  {
    name: "Biology 101",
    code: "BIO101C",
    description: "Introduction to biology.",
    lecturer: "Dr. David Brown",
    students: [],
    unit: "Introduction to Biology",
    startTime: new Date("2024-09-01T14:00:00"),
    endTime: new Date("2024-12-15T16:00:00"),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "4",
  },
  {
    name: "Computer Science 101",
    code: "CS101C",
    description: "Foundations of computer science.",
    lecturer: "Dr. Emma Green",
    students: [],
    unit: "Introduction to Computer Science",
    startTime: new Date("2024-09-01T16:00:00"),
    endTime: new Date("2024-12-15T18:00:00"),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "5",
  },
  {
    name: "Economics 101",
    code: "ECON101C",
    description: "Principles of economics.",
    lecturer: "Dr. Frank Harris",
    students: [],
    unit: "Introduction to Economics",
    startTime: new Date("2024-09-01T08:00:00"),
    endTime: new Date("2024-12-15T10:00:00"),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "6",
  },
  {
    name: "History 101",
    code: "HIST101C",
    description: "Overview of major historical events.",
    lecturer: "Dr. Grace Lewis",
    students: [],
    unit: "Introduction to History",
    startTime: new Date("2024-09-01T10:00:00"),
    endTime: new Date("2024-12-15T12:00:00"),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "7",
  },
  {
    name: "Literature 101",
    code: "LIT101C",
    description: "Study of classic and modern literature.",
    lecturer: "Dr. Henry Clark",
    students: [],
    unit: "Introduction to Literature",
    startTime: new Date("2024-09-01T12:00:00"),
    endTime: new Date("2024-12-15T14:00:00"),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "8",
  },
  {
    name: "Philosophy 101",
    code: "PHIL101C",
    description: "Introduction to philosophical thinking.",
    lecturer: "Dr. Ivy Martinez",
    students: [],
    unit: "Introduction to Philosophy",
    startTime: new Date("2024-09-01T14:00:00"),
    endTime: new Date("2024-12-15T16:00:00"),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "9",
  },
  {
    name: "Psychology 101",
    code: "PSY101C",
    description: "Basic principles of psychology.",
    lecturer: "Dr. Jack Walker",
    students: [],
    unit: "Introduction to Psychology",
    startTime: new Date("2024-09-01T16:00:00"),
    endTime: new Date("2024-12-15T18:00:00"),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
    _id: "10",
  },
];

export type IDummyClass = (typeof dummyClasses)[0];
